ARR = ['I was going to tell you a joke about boxing but I forgot the punch line.',
'I\'m not a fan of spring cleaning. Let\'s be honest, I\'m not into summer, fall, or winter cleaning either.',
'Why did the egg hide? It was a little chicken.',
'What did the dirt say to the rain? If you keep',
'Why couldn\'t the sunflower ride its bike? It l',
'What\'s an egg\'s favorite vacation spot? New Yo',
'I ate a sock yesterday. It was very time-consu',
'What kind of candy do astronauts like? Mars ba',
'I wanted to buy some camo pants but couldn\'t f',
'happy family of three enjoying breakfast at taMorsa Images',
'I ordered a chicken and an egg from Amazon. I',
'What month is the shortest of the year? May, i',
'What did the snail who was riding on the turtl',
'I was going to tell a time traveling joke, but',
'What do you call a lazy kangaroo? A pouch pota',
'I used to run a dating service for chickens, b',
'What does a pig put on dry skin? Ointment.',
'What do you call it when a snowman throws a ta',
'My uncle named his dogs Timex and Rolex. They\'',
'How do you open a banana? With a mon-key.',
'senior woman and adult daughter laughing on poMoMo Productions',
'Which is faster, hot or cold? Hot, because you',
'What did one plate say to the other plate? Din',
'Why do oranges wear sunscreen? So they don\'t p',
'My wife told me to stop acting like a flamingo',
'What do you call a pig that does karate? A por',
'Where does Batman go to the bathroom? The batr',
'What do you call a pony with a sore throat? A',
'What did the left eye say to the right eye? Betwe',
'What did the mama tomato say to the baby tomato? ',
'Why didn\'t the melons get married? Because they c',
'What do you call a fake noodle? An impasta.',
'How did the pig get to the hogspital? In a hambul',
'I\'m so good at sleeping I can do it with my eyes',
'Why does Humpty Dumpty love autumn? Because he ha',
'What happens when a strawberry gets run over cros',
'Why did the cow jump over the moon? The farmer ha',
'A termite walks into a bar and says, "So, is the ',
'How does an octopus go into battle? Well-armed.',
'What do you call a pudgy psychic? A four-chin tel',
'high angle view of cheerful grandparents talking at homepinterest iconKlaus Vedfelt',
'What do you get when you mix a cocker spaniel, a ',
'How do celebrities stay cool? They have many fans',
'What does a pickle say when he wants to play card',
'How much money does a pirate pay for corn? A bucc',
'Where do young trees go to learn? Elementree scho',
'Why do bees have sticky hair? Because they use a ',
'How did the student feel when he learned about el',
'What do you call a bee that can\'t make up its min',
'Why was six afraid of seven? Because 7-8-9.',
'If April showers bring May flowers, what do May f',
'I tried to catch fog yesterday. Mist.',
'What do you call a hippie\'s wife? Mississippi.',
'Two peanuts were walking down the street. One was',
'How can you tell it’s a dogwood tree? By the bark',
'What did the buffalo say when his kid went to col',
'What did the mayonnaise say when the refrigerator',
'What\'s the stinkiest planet? Poopiter.',
'two best friends telling secrets lying in the graND Westend61',
'What did one wall say to the other? I\'ll meet you',
'Why don\'t sharks eat clowns? Because they taste fART',
'A horse walks into a bar. The bartender says, "WTF',
'What did the pirate say when he turned 80? Aye ma',
'What\'s black and white and goes round and round? ',
'How do you organize a space party? You planet.',
'Why couldn\'t the bicycle stand up by itself? It w',
'Did you hear the rumor about butter? Well, I\'m no',
'Why did the student eat his homework? Because his',
'What did one hat say to the other? You wait here,',
'What do you call a dinosaur that crashes his car?',
'I couldn\'t figure out why the baseball kept getti',
'What do you call a boomerang that won’t come back',
'What did the full glass say to the empty glass? Y',
'How do you stop a bull from charging? Cancel its ',
'Why don\’t we see elephants hiding in trees? Becau',
'happy multiracial senior women having fun togethe',
'What\’s the difference between a hippo and a zippo',
'Did you hear the one about the roof? Never mind, ',
'I used to hate facial hair...but then it grew on ',
'A cheese factory exploded in France. Da brie was ',
'What\'s a ninja\'s favorite type of shoes? Sneakers',
'What\'s the best smelling insect? A deodor-ant.',
'What do you call a bear without any teeth? A gumm',
'Why was the coach yelling at the vending machine?']

function Generate(){
    let leng = ARR.length;
    let no = Math.floor(Math.random() * 100);
    no = Number.parseInt(no);
    document.write(ARR[no]);
}